matrix:
  include:
    - language: java
      jdk: openjdk7
      after_success:
        - gradle build --info
    - language: java
      jdk: oraclejdk7
      after_success:
        - gradle build --info
    - language: java
      jdk: oraclejdk8
      after_success:
        - gradle cobertura coveralls --info


