language: java

matrix:
  include:
    - env: SEND_TO_COVERALLS='YES'
      jdk: oraclejdk8
    - env: SEND_TO_COVERALLS='NO'
      jdk: oraclejdk9

script: gradle build --info

after_success:
  - if [ $SEND_TO_COVERALLS == "YES" ]; then
      echo "Send to coveralls"
      gradle cobertura coveralls --info
    fi

notifications:
  email: false