/* Generated By:JJTree: Do not edit this line. ASTHeading.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.koara;


public
class ASTHeading extends ASTBlockElement {
  public ASTHeading(int id) {
    super(id);
  }



  /** Accept the visitor. **/
  public Object jjtAccept(KoaraVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f63d0b6609019acb0a900867d3b7b6eb (do not edit this line) */
