/* Generated By:JJTree: Do not edit this line. ASTListItem.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.koara;

public
class ASTListItem extends SimpleNode {

  private Integer number;
	
  public ASTListItem(int id) {
    super(id);
  }

  public ASTListItem(Koara p, int id) {
    super(p, id);
  }

  public Integer getNumber() {
	return number;
  }
  
  public void setNumber(Integer number) {
	this.number = number;
  }
  
  public Object jjtAccept(KoaraVisitor visitor, Object data) {
	  return visitor.visit(this, data);
  }
}
