/* Generated By:JJTree: Do not edit this line. ASTLineBreak.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.koara;

public
class ASTLineBreak extends SimpleNode {
  public ASTLineBreak(int id) {
    super(id);
  }

  public ASTLineBreak(Koara p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(KoaraVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14f6f9347718b0d67aeff335d1ba3985 (do not edit this line) */
