/* Generated By:JavaCC: Do not edit this line. KoaraDefaultVisitor.java Version 6.0_1 */
package io.koara;

import io.koara.ast.ASTBlockquote;
import io.koara.ast.ASTCode;
import io.koara.ast.ASTCodeBlock;
import io.koara.ast.ASTEm;
import io.koara.ast.ASTHeading;
import io.koara.ast.ASTImage;
import io.koara.ast.ASTLineBreak;
import io.koara.ast.ASTLink;
import io.koara.ast.ASTList;
import io.koara.ast.ASTListItem;
import io.koara.ast.ASTParagraph;
import io.koara.ast.ASTStrong;
import io.koara.ast.ASTText;
import io.koara.ast.Document;

public class KoaraDefaultVisitor implements KoaraVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(Document node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTHeading node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBlockquote node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTListItem node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCodeBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParagraph node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTImage node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLink node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTText node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStrong node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLineBreak node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=36e48f1e85512412accc0106ab67ace2 (do not edit this line) */
