/* Generated By:JJTree&JavaCC: Do not edit this line. KoaraConstants.java */
package io.koara;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KoaraConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASTERISK = 1;
  /** RegularExpression Id. */
  int BACKSLASH = 2;
  /** RegularExpression Id. */
  int BACKTICK = 3;
  /** RegularExpression Id. */
  int CHAR_SEQUENCE = 4;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int DASH = 6;
  /** RegularExpression Id. */
  int DIGITS = 7;
  /** RegularExpression Id. */
  int DOT = 8;
  /** RegularExpression Id. */
  int EOL = 9;
  /** RegularExpression Id. */
  int EQ = 10;
  /** RegularExpression Id. */
  int ESCAPED_CHAR = 11;
  /** RegularExpression Id. */
  int GT = 12;
  /** RegularExpression Id. */
  int IMAGE_LABEL = 13;
  /** RegularExpression Id. */
  int LBRACK = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int LT = 16;
  /** RegularExpression Id. */
  int RBRACK = 17;
  /** RegularExpression Id. */
  int RPAREN = 18;
  /** RegularExpression Id. */
  int SPACE = 19;
  /** RegularExpression Id. */
  int TAB = 20;
  /** RegularExpression Id. */
  int UNDERSCORE = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"*\"",
    "\"\\\\\"",
    "\"`\"",
    "<CHAR_SEQUENCE>",
    "\":\"",
    "\"-\"",
    "<DIGITS>",
    "\".\"",
    "<EOL>",
    "\"=\"",
    "<ESCAPED_CHAR>",
    "\">\"",
    "\"image:\"",
    "\"[\"",
    "\"(\"",
    "\"<\"",
    "\"]\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"_\"",
  };

}
